#importing random package to use it module
import random

def computer_guess(x):
    '''
    (int) -> NoneType

    A random number is generated by computer between low and high where high is initially
    set to x. A feedback is asked from user everytime a number is generated and asked whether
    the number guessed by computer is equal to, less or higher than users number and accordingly the
    low and high are modified.
    '''
    low = 1
    high = x
    feedback = ''
    while feedback != 'c':
        if low != high:
            guess = random.randint(low, high)
        else:
            guess = low
        feedback = input(f"Is {guess} Too high(H), Too low(L) or correct(C) : ").lower()
        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1
    print(f'Yay! computer guessed your number, {guess}, correctly!!!')

computer_guess(1000)